### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [marcosdiez/IngressIntelToGps#2]
Are you planning to push this app on F-Droid?
If yes, are you using proprietary binaries?

I can translate the app, especially if you put the app on F-Droid ! :stuck_out_tongue:

**Comment by marcosdiez** [comment]
I of course do not mind my apps being pushed to the FDroid.
This app has only 10k, so... no libraries at all. Not even google play service.

It only has 3 sentences. I am not sure if it worth translation it to French, but if you want, please go ahead.

Marcos
